[env]
CARGO_NET_GIT_FETCH_WITH_CLI = "true"

# this is for my custom cross compile
# it also need the stub lib file "libcuda.so" "libffi.so"
[target.aarch64-unknown-linux-gnu]
# linker = "/opt/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-linux-gnu-ld"
# rustflags = ["-L", "/opt/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/lib/gcc/aarch64-none-linux-gnu/10.3.1",
#    "-L", "/opt/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin"]
